services:
  - type: web
    name: instagram-webhook-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: VERIFY_TOKEN
        sync: false  # Set this manually in Render dashboard
